-- Migration: Consolidation Reports & AI Insights
-- Adds tables for research consolidation reports and AI-generated insights.
-- These support the research consolidation engine and AI-native features.

-- ─── Consolidation Report Type Enum ────────────────────────────────
CREATE TYPE consolidation_report_type AS ENUM (
  'client_brief_summary',
  'property_comparison',
  'market_analysis',
  'search_progress',
  'due_diligence_summary',
  'settlement_outcome'
);

-- ─── Consolidation Report Status Enum ──────────────────────────────
CREATE TYPE consolidation_report_status AS ENUM (
  'generating',
  'ready',
  'sent_to_client',
  'archived',
  'failed'
);

-- ─── Report Generated By Enum ──────────────────────────────────────
CREATE TYPE report_generated_by AS ENUM (
  'ai',
  'manual',
  'automated'
);

-- ─── Consolidation Reports Table ───────────────────────────────────
CREATE TABLE consolidation_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES contacts(id),
  client_brief_id UUID REFERENCES client_briefs(id),
  transaction_id UUID REFERENCES transactions(id),

  type consolidation_report_type NOT NULL,
  title TEXT NOT NULL,
  status consolidation_report_status NOT NULL DEFAULT 'generating',

  content JSONB NOT NULL DEFAULT '{}',

  generated_by report_generated_by NOT NULL DEFAULT 'ai',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_to_client_at TIMESTAMPTZ,

  version INTEGER NOT NULL DEFAULT 1,
  previous_version_id UUID REFERENCES consolidation_reports(id),

  created_by UUID NOT NULL REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

-- Indexes for common queries
CREATE INDEX idx_consolidation_reports_client_id ON consolidation_reports(client_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_consolidation_reports_type ON consolidation_reports(type) WHERE deleted_at IS NULL;
CREATE INDEX idx_consolidation_reports_status ON consolidation_reports(status) WHERE deleted_at IS NULL;
CREATE INDEX idx_consolidation_reports_client_brief ON consolidation_reports(client_brief_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_consolidation_reports_created_at ON consolidation_reports(created_at DESC) WHERE deleted_at IS NULL;

-- ─── AI Confidence Enum ────────────────────────────────────────────
CREATE TYPE ai_confidence AS ENUM ('high', 'medium', 'low');

-- ─── AI Insight Type Enum ──────────────────────────────────────────
CREATE TYPE ai_insight_type AS ENUM (
  'property_analysis',
  'market_summary',
  'brief_refinement',
  'risk_assessment',
  'recommendation',
  'consolidation_summary'
);

-- ─── AI Insights Table ─────────────────────────────────────────────
-- Stores AI-generated insights that can be attached to any entity.
CREATE TABLE ai_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type ai_insight_type NOT NULL,
  target_type TEXT NOT NULL, -- 'property', 'client_brief', 'transaction', etc.
  target_id UUID NOT NULL,
  client_brief_id UUID REFERENCES client_briefs(id),

  title TEXT,
  content JSONB NOT NULL,
  confidence ai_confidence NOT NULL DEFAULT 'medium',

  model_used TEXT, -- e.g., 'claude-sonnet-4-20250514'
  tokens_used INTEGER,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ -- insights can expire if data changes
);

-- Indexes
CREATE INDEX idx_ai_insights_target ON ai_insights(target_type, target_id);
CREATE INDEX idx_ai_insights_type ON ai_insights(type);
CREATE INDEX idx_ai_insights_brief ON ai_insights(client_brief_id);

-- ─── Market Snapshots Table ────────────────────────────────────────
-- Stores point-in-time market data for suburbs.
-- Used by the consolidation engine and AI market analysis.
CREATE TABLE market_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  suburb TEXT NOT NULL,
  state TEXT NOT NULL,
  postcode TEXT,

  median_price NUMERIC(12,2),
  median_price_change_12m NUMERIC(8,4), -- percentage
  days_on_market INTEGER,
  auction_clearance_rate NUMERIC(5,2), -- percentage
  total_listings INTEGER,

  property_type TEXT, -- optional filter (house, unit, etc.)
  data_source TEXT, -- 'domain', 'rea', 'manual'
  data_as_of TIMESTAMPTZ NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_market_snapshots_suburb ON market_snapshots(suburb, state);
CREATE INDEX idx_market_snapshots_date ON market_snapshots(data_as_of DESC);
CREATE UNIQUE INDEX idx_market_snapshots_unique ON market_snapshots(suburb, state, property_type, data_source, data_as_of);

-- ─── RLS Policies ──────────────────────────────────────────────────

ALTER TABLE consolidation_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_snapshots ENABLE ROW LEVEL SECURITY;

-- Consolidation reports: users can only access their own reports
CREATE POLICY consolidation_reports_select ON consolidation_reports
  FOR SELECT USING (created_by = auth.uid());

CREATE POLICY consolidation_reports_insert ON consolidation_reports
  FOR INSERT WITH CHECK (created_by = auth.uid());

CREATE POLICY consolidation_reports_update ON consolidation_reports
  FOR UPDATE USING (created_by = auth.uid());

-- AI insights: accessible to authenticated users (insights are agent-scoped via the target)
CREATE POLICY ai_insights_select ON ai_insights
  FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY ai_insights_insert ON ai_insights
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Market snapshots: readable by all authenticated users, writable by service role
CREATE POLICY market_snapshots_select ON market_snapshots
  FOR SELECT USING (auth.uid() IS NOT NULL);

-- ─── Updated At Triggers ───────────────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER consolidation_reports_updated_at
  BEFORE UPDATE ON consolidation_reports
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
